image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GET_STRATEGY: clone

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME='pwd'/.gradle

stages:
  - build
  - test

build:
  stage: build
  tags:
    - ugrad
  script:
    - ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew check
  tags:
    - ugrad